fieldLayouts:
  912f2edc-98d9-49bd-8682-1d3033be11c9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: speakers
hasUrls: true
name: Speakers
settings:
  path: '@basePath/uploads/speakers'
sortOrder: 1
type: craft\volumes\Local
url: '@baseURL/uploads/speakers'
