field: a8e1cfbf-5594-4c5e-b1ae-50337be2e3bf
fieldLayouts:
  f2ecc042-ca58-4e69-b5c6-612db2364a3f:
    tabs:
      -
        elements:
          -
            fieldUid: 254c2314-c4c6-4d9f-9be4-aec833ce1e52
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5649d27a-3708-405e-bd3d-a06936f45c8d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 47ebac2d-266a-4703-9cc5-536724542bd6
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0380e6b5-bf9d-4be1-a381-5d45b4151bba
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0380e6b5-bf9d-4be1-a381-5d45b4151bba:
    contentColumnType: boolean
    fieldGroup: null
    handle: extraBottomPadding
    instructions: ''
    name: 'Extra Bottom Padding'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  254c2314-c4c6-4d9f-9be4-aec833ce1e52:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  47ebac2d-266a-4703-9cc5-536724542bd6:
    contentColumnType: string
    fieldGroup: null
    handle: partner
    instructions: ''
    name: Partner
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: 'Select Partners'
      showSiteMenu: true
      source: null
      sources:
        - 'section:4de07478-c039-47a0-897b-67875adf4719'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5649d27a-3708-405e-bd3d-a06936f45c8d:
    contentColumnType: text
    fieldGroup: null
    handle: introContent
    instructions: ''
    name: 'Intro Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: partners
name: Partners
sortOrder: 2
