field: a8e1cfbf-5594-4c5e-b1ae-50337be2e3bf
fieldLayouts:
  05f3e3e5-961e-4344-a127-ab6cda1bb71a:
    tabs:
      -
        elements:
          -
            fieldUid: a4a8ee27-d540-494d-9e7c-247015086ff2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4c99b26-4bdc-43c2-8a67-84392fc76def
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 608c4278-1834-4661-bdf3-74f0c719d543
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  608c4278-1834-4661-bdf3-74f0c719d543:
    contentColumnType: boolean
    fieldGroup: null
    handle: extraBottomPadding
    instructions: ''
    name: 'Extra Bottom Padding'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a4a8ee27-d540-494d-9e7c-247015086ff2:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b4c99b26-4bdc-43c2-8a67-84392fc76def:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: simpleContent
name: 'Simple Content'
sortOrder: 1
