contentColumnType: string
fieldGroup: a15f74ea-ebc2-4656-8557-e13b8b6a612f
handle: accordion
instructions: ''
name: 'Accordion (FAQs etc)'
searchable: false
settings:
  contentTable: '{{%matrixcontent_accordion}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
