contentColumnType: boolean
fieldGroup: a15f74ea-ebc2-4656-8557-e13b8b6a612f
handle: communityEvent
instructions: ''
name: 'Community Event'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
