contentColumnType: string
fieldGroup: a15f74ea-ebc2-4656-8557-e13b8b6a612f
handle: speakers
instructions: ''
name: Speakers
searchable: false
settings:
  contentTable: '{{%matrixcontent_speakers}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
