enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  6e03a237-40f3-4689-812b-c83d4bdd8201:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
