dateModified: 1614877264
email:
  fromEmail: richard@pooleyville.uk
  fromName: Protospace
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: Protospace
  retryDuration: null
  schemaVersion: 3.6.4
  timeZone: Europe/London
